kind: Pod
apiVersion: v1
metadata:
  name: init-test
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sh","-c","echo 'Init started....' sleep 10; echo 'Init completed.'"]

  containers:
  - name: main-container
    image: busybox:latest
    command: ["sh","-c","echo 'main container started.'"]
